services:
  - type: web
    name: farm-genie-bot
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - src/**
        - package.json
        - tsconfig.json
        - render.yaml
        - .render/**
    ignorePaths:
      - node_modules/**
      - .git/**
      - dist/** 